//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toggl.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toggl.Core.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add client.
        /// </summary>
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add description.
        /// </summary>
        public static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/filter clients.
        /// </summary>
        public static string AddFilterClients {
            get {
                return ResourceManager.GetString("AddFilterClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/filter project.
        /// </summary>
        public static string AddFilterProjects {
            get {
                return ResourceManager.GetString("AddFilterProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/filter tags.
        /// </summary>
        public static string AddFilterTags {
            get {
                return ResourceManager.GetString("AddFilterTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a project and tags on the fly.
        /// </summary>
        public static string AddProjectBubbleText {
            get {
                return ResourceManager.GetString("AddProjectBubbleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project/task.
        /// </summary>
        public static string AddProjectTask {
            get {
                return ResourceManager.GetString("AddProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tags.
        /// </summary>
        public static string AddTags {
            get {
                return ResourceManager.GetString("AddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Calendar access.
        /// </summary>
        public static string AllowCalendarAccess {
            get {
                return ResourceManager.GetString("AllowCalendarAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string AlreadyHaveAnAccountQuestionMark {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccountQuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your API token has been reset..
        /// </summary>
        public static string APITokenResetSuccess {
            get {
                return ResourceManager.GetString("APITokenResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems you haven&apos;t updated the app for quite some time...
        ///Please update your app to continue..
        /// </summary>
        public static string AppOutdatedMessage {
            get {
                return ResourceManager.GetString("AppOutdatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggl.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (archived).
        /// </summary>
        public static string ArchivedProjectDecorator {
            get {
                return ResourceManager.GetString("ArchivedProjectDecorator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billable.
        /// </summary>
        public static string Billable {
            get {
                return ResourceManager.GetString("Billable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggl needs access to your calendar in order to display events. Events are visible to you only and won’t appear in Reports..
        /// </summary>
        public static string CalendarAccessExplanation {
            get {
                return ResourceManager.GetString("CalendarAccessExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as a time entry.
        /// </summary>
        public static string CalendarCopyEventToTimeEntry {
            get {
                return ResourceManager.GetString("CalendarCopyEventToTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar feature links to calendars on your device so that you can see events and turn these to time entries..
        /// </summary>
        public static string CalendarFeatureDescription {
            get {
                return ResourceManager.GetString("CalendarFeatureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Settings.
        /// </summary>
        public static string CalendarSettingsTitle {
            get {
                return ResourceManager.GetString("CalendarSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start now.
        /// </summary>
        public static string CalendarStartNow {
            get {
                return ResourceManager.GetString("CalendarStartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start at event start.
        /// </summary>
        public static string CalendarStartWhenTheEventStarts {
            get {
                return ResourceManager.GetString("CalendarStartWhenTheEventStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to do with this calendar event?.
        /// </summary>
        public static string CalendarWhatToDoWithCalendarEvent {
            get {
                return ResourceManager.GetString("CalendarWhatToDoWithCalendarEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorize your time with projects.
        /// </summary>
        public static string CategorizeYourTimeWithProjects {
            get {
                return ResourceManager.GetString("CategorizeYourTimeWithProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clocked hours.
        /// </summary>
        public static string ClockedHours {
            get {
                return ResourceManager.GetString("ClockedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm changes.
        /// </summary>
        public static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Editing.
        /// </summary>
        public static string ContinueEditing {
            get {
                return ResourceManager.GetString("ContinueEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue last entry.
        /// </summary>
        public static string ContinueLastEntry {
            get {
                return ResourceManager.GetString("ContinueLastEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue timer.
        /// </summary>
        public static string ContinueTimerInvocationPhrase {
            get {
                return ResourceManager.GetString("ContinueTimerInvocationPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without the access.
        /// </summary>
        public static string ContinueWithoutAccess {
            get {
                return ResourceManager.GetString("ContinueWithoutAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:235,&quot;name&quot;:&quot;United States&quot;,&quot;vat_applicable&quot;:false,&quot;vat_regex&quot;:null,&quot;vat_percentage&quot;:null,&quot;country_code&quot;:&quot;US&quot;},{&quot;id&quot;:40,&quot;name&quot;:&quot;Canada&quot;,&quot;vat_applicable&quot;:false,&quot;vat_regex&quot;:null,&quot;vat_percentage&quot;:null,&quot;country_code&quot;:&quot;CA&quot;},{&quot;id&quot;:82,&quot;name&quot;:&quot;Germany&quot;,&quot;vat_applicable&quot;:true,&quot;vat_regex&quot;:&quot;^DE[0-9]{9}$&quot;,&quot;vat_percentage&quot;:19,&quot;country_code&quot;:&quot;DE&quot;},{&quot;id&quot;:111,&quot;name&quot;:&quot;Japan&quot;,&quot;vat_applicable&quot;:false,&quot;vat_regex&quot;:null,&quot;vat_percentage&quot;:null,&quot;country_code&quot;:&quot;JP&quot;},{&quot;id&quot;:156,&quot;name&quot;:&quot;Netherlands&quot;,&quot;vat_applicable&quot;:true,&quot;vat_regex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CountriesJson {
            get {
                return ResourceManager.GetString("CountriesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of residence.
        /// </summary>
        public static string CountryOfResidence {
            get {
                return ResourceManager.GetString("CountryOfResidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create client.
        /// </summary>
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new workspace.
        /// </summary>
        public static string CreateNewWorkspace {
            get {
                return ResourceManager.GetString("CreateNewWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tag.
        /// </summary>
        public static string CreateTag {
            get {
                return ResourceManager.GetString("CreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently delete {0} time entries?.
        /// </summary>
        public static string DeleteMultipleTimeEntries {
            get {
                return ResourceManager.GetString("DeleteMultipleTimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0} time entries.
        /// </summary>
        public static string DeleteNTimeEntries {
            get {
                return ResourceManager.GetString("DeleteNTimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this entry.
        /// </summary>
        public static string DeleteThisEntry {
            get {
                return ResourceManager.GetString("DeleteThisEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this time entry?.
        /// </summary>
        public static string DeleteThisTimeEntry {
            get {
                return ResourceManager.GetString("DeleteThisTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change workspace?.
        /// </summary>
        public static string DifferentWorkspaceAlertMessage {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected a project from another workspace..
        /// </summary>
        public static string DifferentWorkspaceAlertTitle {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard changes?.
        /// </summary>
        public static string DiscardEditingChanges {
            get {
                return ResourceManager.GetString("DiscardEditingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard message?.
        /// </summary>
        public static string DiscardMessage {
            get {
                return ResourceManager.GetString("DiscardMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard this time entry?.
        /// </summary>
        public static string DiscardThisTimeEntry {
            get {
                return ResourceManager.GetString("DiscardThisTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string DoneWithExclamationMark {
            get {
                return ResourceManager.GetString("DoneWithExclamationMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string DoNotHaveAnAccountWithQuestionMark {
            get {
                return ResourceManager.GetString("DoNotHaveAnAccountWithQuestionMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration format.
        /// </summary>
        public static string DurationFormat {
            get {
                return ResourceManager.GetString("DurationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic (47:06 min).
        /// </summary>
        public static string DurationFormatClassic {
            get {
                return ResourceManager.GetString("DurationFormatClassic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal (0.79 h).
        /// </summary>
        public static string DurationFormatDecimal {
            get {
                return ResourceManager.GetString("DurationFormatDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improved (0:47:06).
        /// </summary>
        public static string DurationFormatImproved {
            get {
                return ResourceManager.GetString("DurationFormatImproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing {0} time entries.
        /// </summary>
        public static string EditingTimeEntryGroup {
            get {
                return ResourceManager.GetString("EditingTimeEntryGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h:mm tt.
        /// </summary>
        public static string EditingTwelveHoursFormat {
            get {
                return ResourceManager.GetString("EditingTwelveHoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string EditingTwentyFourHoursFormat {
            get {
                return ResourceManager.GetString("EditingTwentyFourHoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email already exists..
        /// </summary>
        public static string EmailIsAlreadyUsedError {
            get {
                return ResourceManager.GetString("EmailIsAlreadyUsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your projects will show up here.
        ///Use them to categorize your time..
        /// </summary>
        public static string EmptyProjectText {
            get {
                return ResourceManager.GetString("EmptyProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your tags will show up here.
        ///Use them to add keywords to your time entries..
        /// </summary>
        public static string EmptyTagText {
            get {
                return ResourceManager.GetString("EmptyTagText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enable access later from the Settings..
        /// </summary>
        public static string EnableAccessLater {
            get {
                return ResourceManager.GetString("EnableAccessLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter project name.
        /// </summary>
        public static string EnterProject {
            get {
                return ResourceManager.GetString("EnterProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter tag name.
        /// </summary>
        public static string EnterTag {
            get {
                return ResourceManager.GetString("EnterTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time entry was deleted.
        /// </summary>
        public static string EntryDeleted {
            get {
                return ResourceManager.GetString("EntryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event reminder.
        /// </summary>
        public static string EventReminder {
            get {
                return ResourceManager.GetString("EventReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us know what you think. Send us your feedback and questions..
        /// </summary>
        public static string FeedbackFieldPlaceholder {
            get {
                return ResourceManager.GetString("FeedbackFieldPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes before.
        /// </summary>
        public static string FifteenMinutes {
            get {
                return ResourceManager.GetString("FifteenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter workspaces.
        /// </summary>
        public static string FilterWorkspaces {
            get {
                return ResourceManager.GetString("FilterWorkspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of the week.
        /// </summary>
        public static string FirstDayOfTheWeek {
            get {
                return ResourceManager.GetString("FirstDayOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes before.
        /// </summary>
        public static string FiveMinutes {
            get {
                return ResourceManager.GetString("FiveMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format settings.
        /// </summary>
        public static string FormatSettings {
            get {
                return ResourceManager.GetString("FormatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string FridayInitial {
            get {
                return ResourceManager.GetString("FridayInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we’re having trouble logging you in.
        ///Please try again..
        /// </summary>
        public static string GenericLoginError {
            get {
                return ResourceManager.GetString("GenericLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we’re having trouble signing you up. Please try again..
        /// </summary>
        public static string GenericSignUpError {
            get {
                return ResourceManager.GetString("GenericSignUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get password reset link.
        /// </summary>
        public static string GetPasswordResetLink {
            get {
                return ResourceManager.GetString("GetPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in with Google.
        /// </summary>
        public static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up with Google.
        /// </summary>
        public static string GoogleSignUp {
            get {
                return ResourceManager.GetString("GoogleSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group similar time entries.
        /// </summary>
        public static string GroupTimeEntries {
            get {
                return ResourceManager.GetString("GroupTimeEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you working on?.
        /// </summary>
        public static string IdleTimerNotification {
            get {
                return ResourceManager.GetString("IdleTimerNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (inaccessible project).
        /// </summary>
        public static string InaccessibleProject {
            get {
                return ResourceManager.GetString("InaccessibleProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This time entry belongs to a workspace that you don&apos;t have access to anymore and it can&apos;t be synced. Move it to a different workspace by changing the project or delete it..
        /// </summary>
        public static string InaccessibleTimeEntryErrorMessage {
            get {
                return ResourceManager.GetString("InaccessibleTimeEntryErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email/password. Please, try again..
        /// </summary>
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please, try again.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week.
        /// </summary>
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year.
        /// </summary>
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t tracked time for a while.
        ///Start the timer and your most used time entries will appear here..
        /// </summary>
        public static string LogEmptyStateText {
            get {
                return ResourceManager.GetString("LogEmptyStateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back!.
        /// </summary>
        public static string LogEmptyStateTitle {
            get {
                return ResourceManager.GetString("LogEmptyStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging you out securely....
        /// </summary>
        public static string LoggingOutSecurely {
            get {
                return ResourceManager.GetString("LoggingOutSecurely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password? .
        /// </summary>
        public static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get help logging in.
        /// </summary>
        public static string LoginGetHelpLoggingIn {
            get {
                return ResourceManager.GetString("LoginGetHelpLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string LoginNextButton {
            get {
                return ResourceManager.GetString("LoginNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string LoginSignUpEmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginSignUpPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual mode.
        /// </summary>
        public static string ManualMode {
            get {
                return ResourceManager.GetString("ManualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add your data manually, instead of tracking in real time..
        /// </summary>
        public static string ManualModeDescription {
            get {
                return ResourceManager.GetString("ManualModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What have you done?.
        /// </summary>
        public static string ManualTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("ManualTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string MondayInitial {
            get {
                return ResourceManager.GetString("MondayInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most recent entry.
        /// </summary>
        public static string MostRecentEntry {
            get {
                return ResourceManager.GetString("MostRecentEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} time entries deleted.
        /// </summary>
        public static string MultipleEntriesDeleted {
            get {
                return ResourceManager.GetString("MultipleEntriesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Time Entry.
        /// </summary>
        public static string NewTimeEntry {
            get {
                return ResourceManager.GetString("NewTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you don&apos;t have any calendars.
        /// </summary>
        public static string NoCalendarsFoundMessage {
            get {
                return ResourceManager.GetString("NoCalendarsFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client.
        /// </summary>
        public static string NoClient {
            get {
                return ResourceManager.GetString("NoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Description.
        /// </summary>
        public static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non billable.
        /// </summary>
        public static string NonBillable {
            get {
                return ResourceManager.GetString("NonBillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project.
        /// </summary>
        public static string NoProject {
            get {
                return ResourceManager.GetString("NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a project @ and categorize your tracked time..
        /// </summary>
        public static string NoProjectsInfoMessage {
            get {
                return ResourceManager.GetString("NoProjectsInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add keywords to your time entries with # tags..
        /// </summary>
        public static string NoTagsInfoMessage {
            get {
                return ResourceManager.GetString("NoTagsInfoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, thanks.
        /// </summary>
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications are currently disabled. If you’d like to recieve notifications, please enable them in the Settings app..
        /// </summary>
        public static string NotificationDisabledNotice {
            get {
                return ResourceManager.GetString("NotificationDisabledNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be notified about upcoming events before they begin..
        /// </summary>
        public static string NotificationSettingExplaination {
            get {
                return ResourceManager.GetString("NotificationSettingExplaination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart Alerts.
        /// </summary>
        public static string NotificationSettingsTitle {
            get {
                return ResourceManager.GetString("NotificationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems someone has removed you from their workspace. No worries. Create a new workspace to continue..
        /// </summary>
        public static string NoWorkspaceErrorMessage {
            get {
                return ResourceManager.GetString("NoWorkspaceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No worries.
        /// </summary>
        public static string NoWorries {
            get {
                return ResourceManager.GetString("NoWorries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Tasks.
        /// </summary>
        public static string NumberOfTasksPlural {
            get {
                return ResourceManager.GetString("NumberOfTasksPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Task.
        /// </summary>
        public static string NumberOfTasksSingular {
            get {
                return ResourceManager.GetString("NumberOfTasksSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume tracking what you do most often.
        /// </summary>
        public static string OnboardingMostUsedPageCopy {
            get {
                return ResourceManager.GetString("OnboardingMostUsedPageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an instant summary of your time with reports.
        /// </summary>
        public static string OnboardingReportsPageCopy {
            get {
                return ResourceManager.GetString("OnboardingReportsPageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your hours
        ///with a single tap.
        /// </summary>
        public static string OnboardingTrackPageCopy {
            get {
                return ResourceManager.GetString("OnboardingTrackPageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour before.
        /// </summary>
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops.
        /// </summary>
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app.
        /// </summary>
        public static string OpenAppAction {
            get {
                return ResourceManager.GetString("OpenAppAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open app and start.
        /// </summary>
        public static string OpenAppAndStartAction {
            get {
                return ResourceManager.GetString("OpenAppAndStartAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings App.
        /// </summary>
        public static string OpenSettingsApp {
            get {
                return ResourceManager.GetString("OpenSettingsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or Sign out.
        /// </summary>
        public static string OrSignOut {
            get {
                return ResourceManager.GetString("OrSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Unknown email. Please check that it&apos;s entered correctly..
        /// </summary>
        public static string PasswordResetEmailDoesNotExistError {
            get {
                return ResourceManager.GetString("PasswordResetEmailDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email to reset your password..
        /// </summary>
        public static string PasswordResetExplanation {
            get {
                return ResourceManager.GetString("PasswordResetExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we’re having trouble resetting your password. Please try again..
        /// </summary>
        public static string PasswordResetGeneralError {
            get {
                return ResourceManager.GetString("PasswordResetGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re offline. Please connect to the internet and try again..
        /// </summary>
        public static string PasswordResetOfflineError {
            get {
                return ResourceManager.GetString("PasswordResetOfflineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link sent. Please, check your email to reset the password..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://toggl.com/legal/privacy.
        /// </summary>
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project color.
        /// </summary>
        public static string ProjectColor {
            get {
                return ResourceManager.GetString("ProjectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this project already exists.
        /// </summary>
        public static string ProjectNameTakenError {
            get {
                return ResourceManager.GetString("ProjectNameTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull down to refresh.
        /// </summary>
        public static string PullDownToRefresh {
            get {
                return ResourceManager.GetString("PullDownToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure, take me there.
        /// </summary>
        public static string RatingCallToActionTitle {
            get {
                return ResourceManager.GetString("RatingCallToActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us what’s wrong.
        /// </summary>
        public static string RatingViewNegativeCallToActionButtonTitle {
            get {
                return ResourceManager.GetString("RatingViewNegativeCallToActionButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you mind giving us some feedback? It’ll really help us improve Toggl..
        /// </summary>
        public static string RatingViewNegativeCallToActionDescription {
            get {
                return ResourceManager.GetString("RatingViewNegativeCallToActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, no worries.
        /// </summary>
        public static string RatingViewNegativeCallToActionTitle {
            get {
                return ResourceManager.GetString("RatingViewNegativeCallToActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate the app.
        /// </summary>
        public static string RatingViewPositiveCallToActionButtonTitle {
            get {
                return ResourceManager.GetString("RatingViewPositiveCallToActionButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you mind rating Toggl in the App Store? Your review really makes a difference..
        /// </summary>
        public static string RatingViewPositiveCallToActionDescription {
            get {
                return ResourceManager.GetString("RatingViewPositiveCallToActionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome!.
        /// </summary>
        public static string RatingViewPositiveCallToActionTitle {
            get {
                return ResourceManager.GetString("RatingViewPositiveCallToActionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release to Refresh.
        /// </summary>
        public static string ReleaseToRefresh {
            get {
                return ResourceManager.GetString("ReleaseToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of a report is 365 days..
        /// </summary>
        public static string ReportTooLongDescription {
            get {
                return ResourceManager.GetString("ReportTooLongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too Long.
        /// </summary>
        public static string ReportTooLongTitle {
            get {
                return ResourceManager.GetString("ReportTooLongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review the Terms.
        /// </summary>
        public static string ReviewTheTerms {
            get {
                return ResourceManager.GetString("ReviewTheTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SaturdayInitial {
            get {
                return ResourceManager.GetString("SaturdayInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select calendars.
        /// </summary>
        public static string SelectCalendars {
            get {
                return ResourceManager.GetString("SelectCalendars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events are visible to you only and won’t appear in Reports..
        /// </summary>
        public static string SelectCalendarsDescription {
            get {
                return ResourceManager.GetString("SelectCalendarsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country....
        /// </summary>
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your time will be automatically tracked under this workspace. You can change it later from the Settings..
        /// </summary>
        public static string SelectDefaultWorkspaceDescription {
            get {
                return ResourceManager.GetString("SelectDefaultWorkspaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select workspace.
        /// </summary>
        public static string SelectWorkspace {
            get {
                return ResourceManager.GetString("SelectWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default workspace.
        /// </summary>
        public static string SetDefaultWorkspace {
            get {
                return ResourceManager.GetString("SetDefaultWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SettingsDialogButtonSignOut {
            get {
                return ResourceManager.GetString("SettingsDialogButtonSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may lose your data if you sign out before the sync is complete..
        /// </summary>
        public static string SettingsSyncInProgressMessage {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re syncing your data.
        /// </summary>
        public static string SettingsSyncInProgressTitle {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have some unsynced data. Any unsynced data will be lost..
        /// </summary>
        public static string SettingsUnsyncedMessage {
            get {
                return ResourceManager.GetString("SettingsUnsyncedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsynced data.
        /// </summary>
        public static string SettingsUnsyncedTitle {
            get {
                return ResourceManager.GetString("SettingsUnsyncedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show my time.
        /// </summary>
        public static string ShowReportsInvocationPhrase {
            get {
                return ResourceManager.GetString("ShowReportsInvocationPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out of Toggl.
        /// </summary>
        public static string SignOutOfToggl {
            get {
                return ResourceManager.GetString("SignOutOfToggl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your country..
        /// </summary>
        public static string SignUpCountryRequired {
            get {
                return ResourceManager.GetString("SignUpCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be at least 6 characters..
        /// </summary>
        public static string SignUpPasswordRequirements {
            get {
                return ResourceManager.GetString("SignUpPasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up for free.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart alerts.
        /// </summary>
        public static string SmartAlerts {
            get {
                return ResourceManager.GetString("SmartAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again.
        /// </summary>
        public static string SomethingWentWrongTryAgain {
            get {
                return ResourceManager.GetString("SomethingWentWrongTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start and stop times.
        /// </summary>
        public static string StartAndStopTime {
            get {
                return ResourceManager.GetString("StartAndStopTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string Startdate {
            get {
                return ResourceManager.GetString("Startdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start in background.
        /// </summary>
        public static string StartInBackgroundAction {
            get {
                return ResourceManager.GetString("StartInBackgroundAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a time entry.
        /// </summary>
        public static string StartTimeEntry {
            get {
                return ResourceManager.GetString("StartTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you working on?.
        /// </summary>
        public static string StartTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("StartTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track time.
        /// </summary>
        public static string StartTimerInvocationPhrase {
            get {
                return ResourceManager.GetString("StartTimerInvocationPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop tracking.
        /// </summary>
        public static string StopTimerInvocationPhrase {
            get {
                return ResourceManager.GetString("StopTimerInvocationPhrase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit feedback.
        /// </summary>
        public static string SubmitFeedback {
            get {
                return ResourceManager.GetString("SubmitFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WORKING ON THESE?.
        /// </summary>
        public static string SuggestionsHeader {
            get {
                return ResourceManager.GetString("SuggestionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SundayInitial {
            get {
                return ResourceManager.GetString("SundayInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe left to delete.
        /// </summary>
        public static string SwipeLeftToDelete {
            get {
                return ResourceManager.GetString("SwipeLeftToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe right to continue.
        /// </summary>
        public static string SwipeRightToContinue {
            get {
                return ResourceManager.GetString("SwipeRightToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        public static string SyncCompleted {
            get {
                return ResourceManager.GetString("SyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing failed.
        /// </summary>
        public static string SyncFailed {
            get {
                return ResourceManager.GetString("SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to edit it.
        /// </summary>
        public static string TapToEditIt {
            get {
                return ResourceManager.GetString("TapToEditIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to retry.
        /// </summary>
        public static string TapToRetry {
            get {
                return ResourceManager.GetString("TapToRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to start timer.
        /// </summary>
        public static string TapToStartTimer {
            get {
                return ResourceManager.GetString("TapToStartTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to stop timer.
        /// </summary>
        public static string TapToStopTimer {
            get {
                return ResourceManager.GetString("TapToStopTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 minutes before.
        /// </summary>
        public static string TenMinutes {
            get {
                return ResourceManager.GetString("TenMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By tapping I Agree, you understand and agree to Toggl’s Terms of Service and Privacy Policy..
        /// </summary>
        public static string TermsOfServiceDialogMessage {
            get {
                return ResourceManager.GetString("TermsOfServiceDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://toggl.com/legal/terms.
        /// </summary>
        public static string TermsOfServiceUrl {
            get {
                return ResourceManager.GetString("TermsOfServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the feedback. If you had any questions, we’ll get back to you soon..
        /// </summary>
        public static string ThankYouForTheFeedback {
            get {
                return ResourceManager.GetString("ThankYouForTheFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 minutes before.
        /// </summary>
        public static string ThirtyMinutes {
            get {
                return ResourceManager.GetString("ThirtyMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month.
        /// </summary>
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This year.
        /// </summary>
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string ThursdayInitial {
            get {
                return ResourceManager.GetString("ThursdayInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} time entries in this group failed to sync. Open specific time entries for details..
        /// </summary>
        public static string TimeEntriesGroupSyncErrorMessage {
            get {
                return ResourceManager.GetString("TimeEntriesGroupSyncErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time entry suggestion.
        /// </summary>
        public static string TimeEntrySuggestion {
            get {
                return ResourceManager.GetString("TimeEntrySuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;Africa/Algiers&quot;,&quot;Africa/Cairo&quot;,&quot;Africa/Casablanca&quot;,&quot;Africa/Harare&quot;,&quot;Africa/Johannesburg&quot;,&quot;Africa/Monrovia&quot;,&quot;Africa/Nairobi&quot;,&quot;America/Adak&quot;,&quot;America/Argentina/Buenos_Aires&quot;,&quot;America/Argentina/San_Juan&quot;,&quot;America/Belem&quot;,&quot;America/Bogota&quot;,&quot;America/Campo_Grande&quot;,&quot;America/Caracas&quot;,&quot;America/Chicago&quot;,&quot;America/Chihuahua&quot;,&quot;America/Costa_Rica&quot;,&quot;America/Cuiaba&quot;,&quot;America/Denver&quot;,&quot;America/Godthab&quot;,&quot;America/Guatemala&quot;,&quot;America/Halifax&quot;,&quot;America/Indiana/Indianapolis&quot;,&quot;America/Juneau&quot;,&quot;America/La_Paz&quot;,&quot;America/Lima&quot;,&quot;Ameri [rest of string was truncated]&quot;;.
        /// </summary>
        public static string TimezonesJson {
            get {
                return ResourceManager.GetString("TimezonesJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password to log back in to your account.
        /// </summary>
        public static string TokenResetInstruction {
            get {
                return ResourceManager.GetString("TokenResetInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try logging in instead..
        /// </summary>
        public static string TryLoggingInInstead {
            get {
                return ResourceManager.GetString("TryLoggingInInstead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string TuesdayInitial {
            get {
                return ResourceManager.GetString("TuesdayInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h tt.
        /// </summary>
        public static string TwelveHoursFormat {
            get {
                return ResourceManager.GetString("TwelveHoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        public static string TwentyFourHoursFormat {
            get {
                return ResourceManager.GetString("TwentyFourHoursFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh oh..
        /// </summary>
        public static string UhOh {
            get {
                return ResourceManager.GetString("UhOh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNDO.
        /// </summary>
        public static string UndoButtonTitle {
            get {
                return ResourceManager.GetString("UndoButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string UnitHour {
            get {
                return ResourceManager.GetString("UnitHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string UnitMin {
            get {
                return ResourceManager.GetString("UnitMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string UnitSecond {
            get {
                return ResourceManager.GetString("UnitSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming event.
        /// </summary>
        public static string UpcomingEvent {
            get {
                return ResourceManager.GetString("UpcomingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update the app.
        /// </summary>
        public static string UpdateTheApp {
            get {
                return ResourceManager.GetString("UpdateTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use 24-hour clock.
        /// </summary>
        public static string Use24HourClock {
            get {
                return ResourceManager.GetString("Use24HourClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string WednesdayInitial {
            get {
                return ResourceManager.GetString("WednesdayInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When event starts.
        /// </summary>
        public static string WhenEventStarts {
            get {
                return ResourceManager.GetString("WhenEventStarts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on these?.
        /// </summary>
        public static string WorkingOnThese {
            get {
                return ResourceManager.GetString("WorkingOnThese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on this?.
        /// </summary>
        public static string WorkingOnThis {
            get {
                return ResourceManager.GetString("WorkingOnThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace.
        /// </summary>
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your project and time entry will be allocated to the selected workspace..
        /// </summary>
        public static string WorkspaceChangedAlertMessage {
            get {
                return ResourceManager.GetString("WorkspaceChangedAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve changed workspace..
        /// </summary>
        public static string WorkspaceChangedAlertTitle {
            get {
                return ResourceManager.GetString("WorkspaceChangedAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspaces.
        /// </summary>
        public static string Workspaces {
            get {
                return ResourceManager.GetString("Workspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve created your first time entry.
        /// </summary>
        public static string YouHaveCreatedYourFirstTimeEntry {
            get {
                return ResourceManager.GetString("YouHaveCreatedYourFirstTimeEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Profile.
        /// </summary>
        public static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
    }
}
