//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toggl.Shared {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Toggl.Shared.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        public static string OnboardingTrackPageCopy {
            get {
                return ResourceManager.GetString("OnboardingTrackPageCopy", resourceCulture);
            }
        }
        
        public static string OnboardingMostUsedPageCopy {
            get {
                return ResourceManager.GetString("OnboardingMostUsedPageCopy", resourceCulture);
            }
        }
        
        public static string OnboardingReportsPageCopy {
            get {
                return ResourceManager.GetString("OnboardingReportsPageCopy", resourceCulture);
            }
        }
        
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        public static string LoginSignUpEmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpEmailPlaceholder", resourceCulture);
            }
        }
        
        public static string LoginSignUpPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string SignUpPasswordRequirements {
            get {
                return ResourceManager.GetString("SignUpPasswordRequirements", resourceCulture);
            }
        }
        
        public static string LoginNextButton {
            get {
                return ResourceManager.GetString("LoginNextButton", resourceCulture);
            }
        }
        
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        public static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        public static string LoginGetHelpLoggingIn {
            get {
                return ResourceManager.GetString("LoginGetHelpLoggingIn", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        public static string GenericLoginError {
            get {
                return ResourceManager.GetString("GenericLoginError", resourceCulture);
            }
        }
        
        public static string GenericSignUpError {
            get {
                return ResourceManager.GetString("GenericSignUpError", resourceCulture);
            }
        }
        
        public static string StartTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("StartTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        public static string ManualTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("ManualTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string SettingsSyncInProgressTitle {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressTitle", resourceCulture);
            }
        }
        
        public static string SettingsSyncInProgressMessage {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressMessage", resourceCulture);
            }
        }
        
        public static string SettingsUnsyncedTitle {
            get {
                return ResourceManager.GetString("SettingsUnsyncedTitle", resourceCulture);
            }
        }
        
        public static string SettingsUnsyncedMessage {
            get {
                return ResourceManager.GetString("SettingsUnsyncedMessage", resourceCulture);
            }
        }
        
        public static string SettingsDialogButtonSignOut {
            get {
                return ResourceManager.GetString("SettingsDialogButtonSignOut", resourceCulture);
            }
        }
        
        public static string UnitHour {
            get {
                return ResourceManager.GetString("UnitHour", resourceCulture);
            }
        }
        
        public static string UnitMin {
            get {
                return ResourceManager.GetString("UnitMin", resourceCulture);
            }
        }
        
        public static string UnitSecond {
            get {
                return ResourceManager.GetString("UnitSecond", resourceCulture);
            }
        }
        
        public static string SuggestionsHeader {
            get {
                return ResourceManager.GetString("SuggestionsHeader", resourceCulture);
            }
        }
        
        public static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        public static string NoProject {
            get {
                return ResourceManager.GetString("NoProject", resourceCulture);
            }
        }
        
        public static string NoDescription {
            get {
                return ResourceManager.GetString("NoDescription", resourceCulture);
            }
        }
        
        public static string InaccessibleProject {
            get {
                return ResourceManager.GetString("InaccessibleProject", resourceCulture);
            }
        }
        
        public static string WorkspacePlaceholder {
            get {
                return ResourceManager.GetString("WorkspacePlaceholder", resourceCulture);
            }
        }
        
        public static string ProjectPlaceholder {
            get {
                return ResourceManager.GetString("ProjectPlaceholder", resourceCulture);
            }
        }
        
        public static string TaskPlaceholder {
            get {
                return ResourceManager.GetString("TaskPlaceholder", resourceCulture);
            }
        }
        
        public static string TagPlaceholder {
            get {
                return ResourceManager.GetString("TagPlaceholder", resourceCulture);
            }
        }
        
        public static string SyncCompleted {
            get {
                return ResourceManager.GetString("SyncCompleted", resourceCulture);
            }
        }
        
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        public static string SyncFailed {
            get {
                return ResourceManager.GetString("SyncFailed", resourceCulture);
            }
        }
        
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        public static string PullDownToRefresh {
            get {
                return ResourceManager.GetString("PullDownToRefresh", resourceCulture);
            }
        }
        
        public static string ReleaseToRefresh {
            get {
                return ResourceManager.GetString("ReleaseToRefresh", resourceCulture);
            }
        }
        
        public static string LogEmptyStateTitle {
            get {
                return ResourceManager.GetString("LogEmptyStateTitle", resourceCulture);
            }
        }
        
        public static string LogEmptyStateText {
            get {
                return ResourceManager.GetString("LogEmptyStateText", resourceCulture);
            }
        }
        
        public static string DifferentWorkspaceAlertTitle {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertTitle", resourceCulture);
            }
        }
        
        public static string DifferentWorkspaceAlertMessage {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertMessage", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        public static string ConfirmDeleteNewTETitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteNewTETitle", resourceCulture);
            }
        }
        
        public static string ContinueEditing {
            get {
                return ResourceManager.GetString("ContinueEditing", resourceCulture);
            }
        }
        
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        public static string TermsOfServiceUrl {
            get {
                return ResourceManager.GetString("TermsOfServiceUrl", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        public static string NoClient {
            get {
                return ResourceManager.GetString("NoClient", resourceCulture);
            }
        }
        
        public static string AddFilterTags {
            get {
                return ResourceManager.GetString("AddFilterTags", resourceCulture);
            }
        }
        
        public static string AddFilterProjects {
            get {
                return ResourceManager.GetString("AddFilterProjects", resourceCulture);
            }
        }
        
        public static string AddFilterClients {
            get {
                return ResourceManager.GetString("AddFilterClients", resourceCulture);
            }
        }
        
        public static string CreateTag {
            get {
                return ResourceManager.GetString("CreateTag", resourceCulture);
            }
        }
        
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        public static string Workspace {
            get {
                return ResourceManager.GetString("Workspace", resourceCulture);
            }
        }
        
        public static string Workspaces {
            get {
                return ResourceManager.GetString("Workspaces", resourceCulture);
            }
        }
        
        public static string SetDefaultWorkspace {
            get {
                return ResourceManager.GetString("SetDefaultWorkspace", resourceCulture);
            }
        }
        
        public static string EnterTag {
            get {
                return ResourceManager.GetString("EnterTag", resourceCulture);
            }
        }
        
        public static string EnterProject {
            get {
                return ResourceManager.GetString("EnterProject", resourceCulture);
            }
        }
        
        public static string PasswordResetExplanation {
            get {
                return ResourceManager.GetString("PasswordResetExplanation", resourceCulture);
            }
        }
        
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        public static string PasswordResetEmailDoesNotExistError {
            get {
                return ResourceManager.GetString("PasswordResetEmailDoesNotExistError", resourceCulture);
            }
        }
        
        public static string PasswordResetGeneralError {
            get {
                return ResourceManager.GetString("PasswordResetGeneralError", resourceCulture);
            }
        }
        
        public static string PasswordResetOfflineError {
            get {
                return ResourceManager.GetString("PasswordResetOfflineError", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        public static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        public static string GoogleSignUp {
            get {
                return ResourceManager.GetString("GoogleSignUp", resourceCulture);
            }
        }
        
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        public static string LastYear {
            get {
                return ResourceManager.GetString("LastYear", resourceCulture);
            }
        }
        
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        public static string ReportPeriod {
            get {
                return ResourceManager.GetString("ReportPeriod", resourceCulture);
            }
        }
        
        public static string SiriReportPeriodInstruction {
            get {
                return ResourceManager.GetString("SiriReportPeriodInstruction", resourceCulture);
            }
        }
        
        public static string SiriCustomTimeEntryInstruction {
            get {
                return ResourceManager.GetString("SiriCustomTimeEntryInstruction", resourceCulture);
            }
        }
        
        public static string WorkingOnThis {
            get {
                return ResourceManager.GetString("WorkingOnThis", resourceCulture);
            }
        }
        
        public static string WorkingOnThese {
            get {
                return ResourceManager.GetString("WorkingOnThese", resourceCulture);
            }
        }
        
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        public static string NoTagsInfoMessage {
            get {
                return ResourceManager.GetString("NoTagsInfoMessage", resourceCulture);
            }
        }
        
        public static string NoProjectsInfoMessage {
            get {
                return ResourceManager.GetString("NoProjectsInfoMessage", resourceCulture);
            }
        }
        
        public static string MondayInitial {
            get {
                return ResourceManager.GetString("MondayInitial", resourceCulture);
            }
        }
        
        public static string TuesdayInitial {
            get {
                return ResourceManager.GetString("TuesdayInitial", resourceCulture);
            }
        }
        
        public static string WednesdayInitial {
            get {
                return ResourceManager.GetString("WednesdayInitial", resourceCulture);
            }
        }
        
        public static string ThursdayInitial {
            get {
                return ResourceManager.GetString("ThursdayInitial", resourceCulture);
            }
        }
        
        public static string FridayInitial {
            get {
                return ResourceManager.GetString("FridayInitial", resourceCulture);
            }
        }
        
        public static string SaturdayInitial {
            get {
                return ResourceManager.GetString("SaturdayInitial", resourceCulture);
            }
        }
        
        public static string SundayInitial {
            get {
                return ResourceManager.GetString("SundayInitial", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string WorkspaceChangedAlertTitle {
            get {
                return ResourceManager.GetString("WorkspaceChangedAlertTitle", resourceCulture);
            }
        }
        
        public static string WorkspaceChangedAlertMessage {
            get {
                return ResourceManager.GetString("WorkspaceChangedAlertMessage", resourceCulture);
            }
        }
        
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        public static string StartTimeEntry {
            get {
                return ResourceManager.GetString("StartTimeEntry", resourceCulture);
            }
        }
        
        public static string MostRecentEntry {
            get {
                return ResourceManager.GetString("MostRecentEntry", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string DeleteThisTimeEntry {
            get {
                return ResourceManager.GetString("DeleteThisTimeEntry", resourceCulture);
            }
        }
        
        public static string DeleteMultipleTimeEntries {
            get {
                return ResourceManager.GetString("DeleteMultipleTimeEntries", resourceCulture);
            }
        }
        
        public static string DeleteThisEntry {
            get {
                return ResourceManager.GetString("DeleteThisEntry", resourceCulture);
            }
        }
        
        public static string DeleteNTimeEntries {
            get {
                return ResourceManager.GetString("DeleteNTimeEntries", resourceCulture);
            }
        }
        
        public static string DiscardThisTimeEntry {
            get {
                return ResourceManager.GetString("DiscardThisTimeEntry", resourceCulture);
            }
        }
        
        public static string DiscardEditingChanges {
            get {
                return ResourceManager.GetString("DiscardEditingChanges", resourceCulture);
            }
        }
        
        public static string DurationFormatClassic {
            get {
                return ResourceManager.GetString("DurationFormatClassic", resourceCulture);
            }
        }
        
        public static string DurationFormatImproved {
            get {
                return ResourceManager.GetString("DurationFormatImproved", resourceCulture);
            }
        }
        
        public static string DurationFormatDecimal {
            get {
                return ResourceManager.GetString("DurationFormatDecimal", resourceCulture);
            }
        }
        
        public static string ContinueLastEntry {
            get {
                return ResourceManager.GetString("ContinueLastEntry", resourceCulture);
            }
        }
        
        public static string TapToRetry {
            get {
                return ResourceManager.GetString("TapToRetry", resourceCulture);
            }
        }
        
        public static string TimeEntrySuggestion {
            get {
                return ResourceManager.GetString("TimeEntrySuggestion", resourceCulture);
            }
        }
        
        public static string EmailIsAlreadyUsedError {
            get {
                return ResourceManager.GetString("EmailIsAlreadyUsedError", resourceCulture);
            }
        }
        
        public static string TryLoggingInInstead {
            get {
                return ResourceManager.GetString("TryLoggingInInstead", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string SignUpCountryRequired {
            get {
                return ResourceManager.GetString("SignUpCountryRequired", resourceCulture);
            }
        }
        
        public static string CountriesJson {
            get {
                return ResourceManager.GetString("CountriesJson", resourceCulture);
            }
        }
        
        public static string TimezonesJson {
            get {
                return ResourceManager.GetString("TimezonesJson", resourceCulture);
            }
        }
        
        public static string GetPasswordResetLink {
            get {
                return ResourceManager.GetString("GetPasswordResetLink", resourceCulture);
            }
        }
        
        public static string TermsOfServiceDialogMessage {
            get {
                return ResourceManager.GetString("TermsOfServiceDialogMessage", resourceCulture);
            }
        }
        
        public static string CountryOfResidence {
            get {
                return ResourceManager.GetString("CountryOfResidence", resourceCulture);
            }
        }
        
        public static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        public static string RatingViewPositiveCallToActionTitle {
            get {
                return ResourceManager.GetString("RatingViewPositiveCallToActionTitle", resourceCulture);
            }
        }
        
        public static string RatingViewNegativeCallToActionTitle {
            get {
                return ResourceManager.GetString("RatingViewNegativeCallToActionTitle", resourceCulture);
            }
        }
        
        public static string RatingViewPositiveCallToActionDescription {
            get {
                return ResourceManager.GetString("RatingViewPositiveCallToActionDescription", resourceCulture);
            }
        }
        
        public static string RatingViewNegativeCallToActionDescription {
            get {
                return ResourceManager.GetString("RatingViewNegativeCallToActionDescription", resourceCulture);
            }
        }
        
        public static string RatingViewPositiveCallToActionButtonTitle {
            get {
                return ResourceManager.GetString("RatingViewPositiveCallToActionButtonTitle", resourceCulture);
            }
        }
        
        public static string RatingViewNegativeCallToActionButtonTitle {
            get {
                return ResourceManager.GetString("RatingViewNegativeCallToActionButtonTitle", resourceCulture);
            }
        }
        
        public static string ReportTooLongTitle {
            get {
                return ResourceManager.GetString("ReportTooLongTitle", resourceCulture);
            }
        }
        
        public static string ReportTooLongDescription {
            get {
                return ResourceManager.GetString("ReportTooLongDescription", resourceCulture);
            }
        }
        
        public static string ArchivedProjectDecorator {
            get {
                return ResourceManager.GetString("ArchivedProjectDecorator", resourceCulture);
            }
        }
        
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string EntryDeleted {
            get {
                return ResourceManager.GetString("EntryDeleted", resourceCulture);
            }
        }
        
        public static string MultipleEntriesDeleted {
            get {
                return ResourceManager.GetString("MultipleEntriesDeleted", resourceCulture);
            }
        }
        
        public static string UndoButtonTitle {
            get {
                return ResourceManager.GetString("UndoButtonTitle", resourceCulture);
            }
        }
        
        public static string SelectWorkspace {
            get {
                return ResourceManager.GetString("SelectWorkspace", resourceCulture);
            }
        }
        
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        public static string NewTimeEntry {
            get {
                return ResourceManager.GetString("NewTimeEntry", resourceCulture);
            }
        }
        
        public static string EventReminder {
            get {
                return ResourceManager.GetString("EventReminder", resourceCulture);
            }
        }
        
        public static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        public static string NoCalendarsFoundMessage {
            get {
                return ResourceManager.GetString("NoCalendarsFoundMessage", resourceCulture);
            }
        }
        
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        public static string WhenEventStarts {
            get {
                return ResourceManager.GetString("WhenEventStarts", resourceCulture);
            }
        }
        
        public static string FiveMinutes {
            get {
                return ResourceManager.GetString("FiveMinutes", resourceCulture);
            }
        }
        
        public static string TenMinutes {
            get {
                return ResourceManager.GetString("TenMinutes", resourceCulture);
            }
        }
        
        public static string FifteenMinutes {
            get {
                return ResourceManager.GetString("FifteenMinutes", resourceCulture);
            }
        }
        
        public static string ThirtyMinutes {
            get {
                return ResourceManager.GetString("ThirtyMinutes", resourceCulture);
            }
        }
        
        public static string OneHour {
            get {
                return ResourceManager.GetString("OneHour", resourceCulture);
            }
        }
        
        public static string CalendarSettingsTitle {
            get {
                return ResourceManager.GetString("CalendarSettingsTitle", resourceCulture);
            }
        }
        
        public static string NotificationSettingsTitle {
            get {
                return ResourceManager.GetString("NotificationSettingsTitle", resourceCulture);
            }
        }
        
        public static string OpenAppAndStartAction {
            get {
                return ResourceManager.GetString("OpenAppAndStartAction", resourceCulture);
            }
        }
        
        public static string StartInBackgroundAction {
            get {
                return ResourceManager.GetString("StartInBackgroundAction", resourceCulture);
            }
        }
        
        public static string OpenAppAction {
            get {
                return ResourceManager.GetString("OpenAppAction", resourceCulture);
            }
        }
        
        public static string IdleTimerNotification {
            get {
                return ResourceManager.GetString("IdleTimerNotification", resourceCulture);
            }
        }
        
        public static string DiscardMessage {
            get {
                return ResourceManager.GetString("DiscardMessage", resourceCulture);
            }
        }
        
        public static string InaccessibleTimeEntryErrorMessage {
            get {
                return ResourceManager.GetString("InaccessibleTimeEntryErrorMessage", resourceCulture);
            }
        }
        
        public static string TimeEntriesGroupSyncErrorMessage {
            get {
                return ResourceManager.GetString("TimeEntriesGroupSyncErrorMessage", resourceCulture);
            }
        }
        
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        public static string CalendarWhatToDoWithCalendarEvent {
            get {
                return ResourceManager.GetString("CalendarWhatToDoWithCalendarEvent", resourceCulture);
            }
        }
        
        public static string CalendarStartNow {
            get {
                return ResourceManager.GetString("CalendarStartNow", resourceCulture);
            }
        }
        
        public static string CalendarStartWhenTheEventStarts {
            get {
                return ResourceManager.GetString("CalendarStartWhenTheEventStarts", resourceCulture);
            }
        }
        
        public static string CalendarCopyEventToTimeEntry {
            get {
                return ResourceManager.GetString("CalendarCopyEventToTimeEntry", resourceCulture);
            }
        }
        
        public static string CreateClient {
            get {
                return ResourceManager.GetString("CreateClient", resourceCulture);
            }
        }
        
        public static string NoWorries {
            get {
                return ResourceManager.GetString("NoWorries", resourceCulture);
            }
        }
        
        public static string EnableAccessLater {
            get {
                return ResourceManager.GetString("EnableAccessLater", resourceCulture);
            }
        }
        
        public static string ContinueWithoutAccess {
            get {
                return ResourceManager.GetString("ContinueWithoutAccess", resourceCulture);
            }
        }
        
        public static string AllowCalendarAccess {
            get {
                return ResourceManager.GetString("AllowCalendarAccess", resourceCulture);
            }
        }
        
        public static string CalendarAccessExplanation {
            get {
                return ResourceManager.GetString("CalendarAccessExplanation", resourceCulture);
            }
        }
        
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        public static string CalendarFeatureDescription {
            get {
                return ResourceManager.GetString("CalendarFeatureDescription", resourceCulture);
            }
        }
        
        public static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        public static string StartAndStopTime {
            get {
                return ResourceManager.GetString("StartAndStopTime", resourceCulture);
            }
        }
        
        public static string ProjectNameTakenError {
            get {
                return ResourceManager.GetString("ProjectNameTakenError", resourceCulture);
            }
        }
        
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        public static string Billable {
            get {
                return ResourceManager.GetString("Billable", resourceCulture);
            }
        }
        
        public static string NonBillable {
            get {
                return ResourceManager.GetString("NonBillable", resourceCulture);
            }
        }
        
        public static string Startdate {
            get {
                return ResourceManager.GetString("Startdate", resourceCulture);
            }
        }
        
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        public static string AddProjectTask {
            get {
                return ResourceManager.GetString("AddProjectTask", resourceCulture);
            }
        }
        
        public static string ConfirmChanges {
            get {
                return ResourceManager.GetString("ConfirmChanges", resourceCulture);
            }
        }
        
        public static string CategorizeYourTimeWithProjects {
            get {
                return ResourceManager.GetString("CategorizeYourTimeWithProjects", resourceCulture);
            }
        }
        
        public static string AddTags {
            get {
                return ResourceManager.GetString("AddTags", resourceCulture);
            }
        }
        
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        public static string DoNotHaveAnAccountWithQuestionMark {
            get {
                return ResourceManager.GetString("DoNotHaveAnAccountWithQuestionMark", resourceCulture);
            }
        }
        
        public static string SwipeRightToContinue {
            get {
                return ResourceManager.GetString("SwipeRightToContinue", resourceCulture);
            }
        }
        
        public static string SwipeLeftToDelete {
            get {
                return ResourceManager.GetString("SwipeLeftToDelete", resourceCulture);
            }
        }
        
        public static string YouHaveCreatedYourFirstTimeEntry {
            get {
                return ResourceManager.GetString("YouHaveCreatedYourFirstTimeEntry", resourceCulture);
            }
        }
        
        public static string TapToEditIt {
            get {
                return ResourceManager.GetString("TapToEditIt", resourceCulture);
            }
        }
        
        public static string TapToStartTimer {
            get {
                return ResourceManager.GetString("TapToStartTimer", resourceCulture);
            }
        }
        
        public static string TapToStopTimer {
            get {
                return ResourceManager.GetString("TapToStopTimer", resourceCulture);
            }
        }
        
        public static string DoneWithExclamationMark {
            get {
                return ResourceManager.GetString("DoneWithExclamationMark", resourceCulture);
            }
        }
        
        public static string ThankYouForTheFeedback {
            get {
                return ResourceManager.GetString("ThankYouForTheFeedback", resourceCulture);
            }
        }
        
        public static string NotificationDisabledNotice {
            get {
                return ResourceManager.GetString("NotificationDisabledNotice", resourceCulture);
            }
        }
        
        public static string OpenSettingsApp {
            get {
                return ResourceManager.GetString("OpenSettingsApp", resourceCulture);
            }
        }
        
        public static string UpcomingEvent {
            get {
                return ResourceManager.GetString("UpcomingEvent", resourceCulture);
            }
        }
        
        public static string NotificationSettingExplaination {
            get {
                return ResourceManager.GetString("NotificationSettingExplaination", resourceCulture);
            }
        }
        
        public static string CreateNewWorkspace {
            get {
                return ResourceManager.GetString("CreateNewWorkspace", resourceCulture);
            }
        }
        
        public static string UhOh {
            get {
                return ResourceManager.GetString("UhOh", resourceCulture);
            }
        }
        
        public static string NoWorkspaceErrorMessage {
            get {
                return ResourceManager.GetString("NoWorkspaceErrorMessage", resourceCulture);
            }
        }
        
        public static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        public static string AppOutdatedMessage {
            get {
                return ResourceManager.GetString("AppOutdatedMessage", resourceCulture);
            }
        }
        
        public static string UpdateTheApp {
            get {
                return ResourceManager.GetString("UpdateTheApp", resourceCulture);
            }
        }
        
        public static string RatingCallToActionTitle {
            get {
                return ResourceManager.GetString("RatingCallToActionTitle", resourceCulture);
            }
        }
        
        public static string NoThanks {
            get {
                return ResourceManager.GetString("NoThanks", resourceCulture);
            }
        }
        
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        public static string ClockedHours {
            get {
                return ResourceManager.GetString("ClockedHours", resourceCulture);
            }
        }
        
        public static string FirstDayOfTheWeek {
            get {
                return ResourceManager.GetString("FirstDayOfTheWeek", resourceCulture);
            }
        }
        
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        public static string ProjectColor {
            get {
                return ResourceManager.GetString("ProjectColor", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        public static string SelectDefaultWorkspaceDescription {
            get {
                return ResourceManager.GetString("SelectDefaultWorkspaceDescription", resourceCulture);
            }
        }
        
        public static string DurationFormat {
            get {
                return ResourceManager.GetString("DurationFormat", resourceCulture);
            }
        }
        
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        public static string EmptyProjectText {
            get {
                return ResourceManager.GetString("EmptyProjectText", resourceCulture);
            }
        }
        
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        public static string EmptyTagText {
            get {
                return ResourceManager.GetString("EmptyTagText", resourceCulture);
            }
        }
        
        public static string GroupTimeEntries {
            get {
                return ResourceManager.GetString("GroupTimeEntries", resourceCulture);
            }
        }
        
        public static string EditingTimeEntryGroup {
            get {
                return ResourceManager.GetString("EditingTimeEntryGroup", resourceCulture);
            }
        }
        
        public static string NumberOfTasksPlural {
            get {
                return ResourceManager.GetString("NumberOfTasksPlural", resourceCulture);
            }
        }
        
        public static string NumberOfTasksSingular {
            get {
                return ResourceManager.GetString("NumberOfTasksSingular", resourceCulture);
            }
        }
        
        public static string SelectCalendars {
            get {
                return ResourceManager.GetString("SelectCalendars", resourceCulture);
            }
        }
        
        public static string SelectCalendarsDescription {
            get {
                return ResourceManager.GetString("SelectCalendarsDescription", resourceCulture);
            }
        }
        
        public static string FilterWorkspaces {
            get {
                return ResourceManager.GetString("FilterWorkspaces", resourceCulture);
            }
        }
        
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        public static string FeedbackFieldPlaceholder {
            get {
                return ResourceManager.GetString("FeedbackFieldPlaceholder", resourceCulture);
            }
        }
        
        public static string SomethingWentWrongTryAgain {
            get {
                return ResourceManager.GetString("SomethingWentWrongTryAgain", resourceCulture);
            }
        }
        
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        public static string YourProfile {
            get {
                return ResourceManager.GetString("YourProfile", resourceCulture);
            }
        }
        
        public static string FormatSettings {
            get {
                return ResourceManager.GetString("FormatSettings", resourceCulture);
            }
        }
        
        public static string Use24HourClock {
            get {
                return ResourceManager.GetString("Use24HourClock", resourceCulture);
            }
        }
        
        public static string ManualMode {
            get {
                return ResourceManager.GetString("ManualMode", resourceCulture);
            }
        }
        
        public static string ManualModeDescription {
            get {
                return ResourceManager.GetString("ManualModeDescription", resourceCulture);
            }
        }
        
        public static string SmartAlerts {
            get {
                return ResourceManager.GetString("SmartAlerts", resourceCulture);
            }
        }
        
        public static string SubmitFeedback {
            get {
                return ResourceManager.GetString("SubmitFeedback", resourceCulture);
            }
        }
        
        public static string LoggingOutSecurely {
            get {
                return ResourceManager.GetString("LoggingOutSecurely", resourceCulture);
            }
        }
        
        public static string SignOutOfToggl {
            get {
                return ResourceManager.GetString("SignOutOfToggl", resourceCulture);
            }
        }
        
        public static string AlreadyHaveAnAccountQuestionMark {
            get {
                return ResourceManager.GetString("AlreadyHaveAnAccountQuestionMark", resourceCulture);
            }
        }
        
        public static string AddProjectBubbleText {
            get {
                return ResourceManager.GetString("AddProjectBubbleText", resourceCulture);
            }
        }
        
        public static string ReviewTheTerms {
            get {
                return ResourceManager.GetString("ReviewTheTerms", resourceCulture);
            }
        }
        
        public static string IAgree {
            get {
                return ResourceManager.GetString("IAgree", resourceCulture);
            }
        }
        
        public static string TokenResetInstruction {
            get {
                return ResourceManager.GetString("TokenResetInstruction", resourceCulture);
            }
        }
        
        public static string OrSignOut {
            get {
                return ResourceManager.GetString("OrSignOut", resourceCulture);
            }
        }
        
        public static string APITokenResetSuccess {
            get {
                return ResourceManager.GetString("APITokenResetSuccess", resourceCulture);
            }
        }
        
        public static string StartTimerInvocationPhrase {
            get {
                return ResourceManager.GetString("StartTimerInvocationPhrase", resourceCulture);
            }
        }
        
        public static string StopTimerInvocationPhrase {
            get {
                return ResourceManager.GetString("StopTimerInvocationPhrase", resourceCulture);
            }
        }
        
        public static string ShowReportsInvocationPhrase {
            get {
                return ResourceManager.GetString("ShowReportsInvocationPhrase", resourceCulture);
            }
        }
        
        public static string ContinueTimerInvocationPhrase {
            get {
                return ResourceManager.GetString("ContinueTimerInvocationPhrase", resourceCulture);
            }
        }
        
        public static string TwelveHoursFormat {
            get {
                return ResourceManager.GetString("TwelveHoursFormat", resourceCulture);
            }
        }
        
        public static string TwentyFourHoursFormat {
            get {
                return ResourceManager.GetString("TwentyFourHoursFormat", resourceCulture);
            }
        }
        
        public static string EditingTwelveHoursFormat {
            get {
                return ResourceManager.GetString("EditingTwelveHoursFormat", resourceCulture);
            }
        }
        
        public static string EditingTwentyFourHoursFormat {
            get {
                return ResourceManager.GetString("EditingTwentyFourHoursFormat", resourceCulture);
            }
        }
        
        public static string Siri_Shortcuts {
            get {
                return ResourceManager.GetString("Siri Shortcuts", resourceCulture);
            }
        }
        
        public static string Siri_Shortcuts_Description {
            get {
                return ResourceManager.GetString("Siri Shortcuts Description", resourceCulture);
            }
        }
        
        public static string Siri_Workflows_Description {
            get {
                return ResourceManager.GetString("Siri Workflows Description", resourceCulture);
            }
        }
        
        public static string SiriShortcutCustomTimeEntryTitle {
            get {
                return ResourceManager.GetString("SiriShortcutCustomTimeEntryTitle", resourceCulture);
            }
        }
        
        public static string SiriShortcutDescriptionFromClipboard {
            get {
                return ResourceManager.GetString("SiriShortcutDescriptionFromClipboard", resourceCulture);
            }
        }
        
        public static string SiriClipboardInstructionTitle {
            get {
                return ResourceManager.GetString("SiriClipboardInstructionTitle", resourceCulture);
            }
        }
        
        public static string SiriClipboardInstructionDescription {
            get {
                return ResourceManager.GetString("SiriClipboardInstructionDescription", resourceCulture);
            }
        }
        
        public static string SiriClipboardInstructionDoNotShowAgain {
            get {
                return ResourceManager.GetString("SiriClipboardInstructionDoNotShowAgain", resourceCulture);
            }
        }
        
        public static string SiriClipboardHintLabel {
            get {
                return ResourceManager.GetString("SiriClipboardHintLabel", resourceCulture);
            }
        }
        
        public static string Siri_Workflows {
            get {
                return ResourceManager.GetString("Siri Workflows", resourceCulture);
            }
        }
        
        public static string CantOpenWorkflowTitle {
            get {
                return ResourceManager.GetString("CantOpenWorkflowTitle", resourceCulture);
            }
        }
        
        public static string CantOpenWorkflowDescription {
            get {
                return ResourceManager.GetString("CantOpenWorkflowDescription", resourceCulture);
            }
        }
        
        public static string SiriTrackEntrySuggestedInvocationPhrase {
            get {
                return ResourceManager.GetString("SiriTrackEntrySuggestedInvocationPhrase", resourceCulture);
            }
        }
        
        public static string SiriShowReportSuggestedInvocationPhrase {
            get {
                return ResourceManager.GetString("SiriShowReportSuggestedInvocationPhrase", resourceCulture);
            }
        }
        
        public static string SiriStartTimerConfirmationMessage {
            get {
                return ResourceManager.GetString("SiriStartTimerConfirmationMessage", resourceCulture);
            }
        }
        
        public static string SiriStartTimerWithEmptyDescConfirmationMessage {
            get {
                return ResourceManager.GetString("SiriStartTimerWithEmptyDescConfirmationMessage", resourceCulture);
            }
        }
        
        public static string SiriStopTimerConfirmationMessage {
            get {
                return ResourceManager.GetString("SiriStopTimerConfirmationMessage", resourceCulture);
            }
        }
        
        public static string SiriStopTimerWithEmptyDescConfirmationMessage {
            get {
                return ResourceManager.GetString("SiriStopTimerWithEmptyDescConfirmationMessage", resourceCulture);
            }
        }
        
        public static string SiriShortcutLoginToUseShortcut {
            get {
                return ResourceManager.GetString("SiriShortcutLoginToUseShortcut", resourceCulture);
            }
        }
        
        public static string SiriShortcutOpenTheAppToSync {
            get {
                return ResourceManager.GetString("SiriShortcutOpenTheAppToSync", resourceCulture);
            }
        }
        
        public static string SiriDurationWithSeconds {
            get {
                return ResourceManager.GetString("SiriDurationWithSeconds", resourceCulture);
            }
        }
        
        public static string SiriDurationWithMinutesAndSeconds {
            get {
                return ResourceManager.GetString("SiriDurationWithMinutesAndSeconds", resourceCulture);
            }
        }
        
        public static string SiriDurationWithHoursAndSeconds {
            get {
                return ResourceManager.GetString("SiriDurationWithHoursAndSeconds", resourceCulture);
            }
        }
        
        public static string SiriDurationWithHoursMinutesAndSeconds {
            get {
                return ResourceManager.GetString("SiriDurationWithHoursMinutesAndSeconds", resourceCulture);
            }
        }
        
        public static string SiriNoCurrentEntryRunning {
            get {
                return ResourceManager.GetString("SiriNoCurrentEntryRunning", resourceCulture);
            }
        }
    }
}
