//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toggl.Foundation {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Toggl.Foundation.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string OnboardingTrackPageCopy {
            get {
                return ResourceManager.GetString("OnboardingTrackPageCopy", resourceCulture);
            }
        }
        
        public static string OnboardingMostUsedPageCopy {
            get {
                return ResourceManager.GetString("OnboardingMostUsedPageCopy", resourceCulture);
            }
        }
        
        public static string OnboardingReportsPageCopy {
            get {
                return ResourceManager.GetString("OnboardingReportsPageCopy", resourceCulture);
            }
        }
        
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        public static string LoginSignUpEmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpEmailPlaceholder", resourceCulture);
            }
        }
        
        public static string LoginSignUpPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string SignUpPasswordRequirements {
            get {
                return ResourceManager.GetString("SignUpPasswordRequirements", resourceCulture);
            }
        }
        
        public static string LoginNextButton {
            get {
                return ResourceManager.GetString("LoginNextButton", resourceCulture);
            }
        }
        
        public static string LoginBackButton {
            get {
                return ResourceManager.GetString("LoginBackButton", resourceCulture);
            }
        }
        
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        public static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        public static string LoginGetHelpLoggingIn {
            get {
                return ResourceManager.GetString("LoginGetHelpLoggingIn", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        public static string GenericLoginError {
            get {
                return ResourceManager.GetString("GenericLoginError", resourceCulture);
            }
        }
        
        public static string GenericSignUpError {
            get {
                return ResourceManager.GetString("GenericSignUpError", resourceCulture);
            }
        }
        
        public static string StartTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("StartTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        public static string ManualTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("ManualTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string SettingsSyncInProgressTitle {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressTitle", resourceCulture);
            }
        }
        
        public static string SettingsSyncInProgressMessage {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressMessage", resourceCulture);
            }
        }
        
        public static string SettingsUnsyncedTitle {
            get {
                return ResourceManager.GetString("SettingsUnsyncedTitle", resourceCulture);
            }
        }
        
        public static string SettingsUnsyncedMessage {
            get {
                return ResourceManager.GetString("SettingsUnsyncedMessage", resourceCulture);
            }
        }
        
        public static string SettingsDialogButtonSignOut {
            get {
                return ResourceManager.GetString("SettingsDialogButtonSignOut", resourceCulture);
            }
        }
        
        public static string UnitHour {
            get {
                return ResourceManager.GetString("UnitHour", resourceCulture);
            }
        }
        
        public static string UnitMin {
            get {
                return ResourceManager.GetString("UnitMin", resourceCulture);
            }
        }
        
        public static string UnitSecond {
            get {
                return ResourceManager.GetString("UnitSecond", resourceCulture);
            }
        }
        
        public static string SuggestionsHeader {
            get {
                return ResourceManager.GetString("SuggestionsHeader", resourceCulture);
            }
        }
        
        public static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        public static string NoProject {
            get {
                return ResourceManager.GetString("NoProject", resourceCulture);
            }
        }
        
        public static string SyncCompleted {
            get {
                return ResourceManager.GetString("SyncCompleted", resourceCulture);
            }
        }
        
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        public static string SyncFailed {
            get {
                return ResourceManager.GetString("SyncFailed", resourceCulture);
            }
        }
        
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        public static string PullDownToRefresh {
            get {
                return ResourceManager.GetString("PullDownToRefresh", resourceCulture);
            }
        }
        
        public static string ReleaseToRefresh {
            get {
                return ResourceManager.GetString("ReleaseToRefresh", resourceCulture);
            }
        }
        
        public static string LogEmptyStateTitle {
            get {
                return ResourceManager.GetString("LogEmptyStateTitle", resourceCulture);
            }
        }
        
        public static string LogEmptyStateText {
            get {
                return ResourceManager.GetString("LogEmptyStateText", resourceCulture);
            }
        }
        
        public static string DifferentWorkspaceAlertTitle {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertTitle", resourceCulture);
            }
        }
        
        public static string DifferentWorkspaceAlertMessage {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertMessage", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string ContinueEditing {
            get {
                return ResourceManager.GetString("ContinueEditing", resourceCulture);
            }
        }
        
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        public static string PrivacyPolicyUrl {
            get {
                return ResourceManager.GetString("PrivacyPolicyUrl", resourceCulture);
            }
        }
        
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        public static string TermsOfServiceUrl {
            get {
                return ResourceManager.GetString("TermsOfServiceUrl", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        public static string NoClient {
            get {
                return ResourceManager.GetString("NoClient", resourceCulture);
            }
        }
        
        public static string AddFilterTags {
            get {
                return ResourceManager.GetString("AddFilterTags", resourceCulture);
            }
        }
        
        public static string AddFilterProjects {
            get {
                return ResourceManager.GetString("AddFilterProjects", resourceCulture);
            }
        }
        
        public static string CreateTag {
            get {
                return ResourceManager.GetString("CreateTag", resourceCulture);
            }
        }
        
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        public static string Workspaces {
            get {
                return ResourceManager.GetString("Workspaces", resourceCulture);
            }
        }
        
        public static string SetDefaultWorkspace {
            get {
                return ResourceManager.GetString("SetDefaultWorkspace", resourceCulture);
            }
        }
        
        public static string EnterTag {
            get {
                return ResourceManager.GetString("EnterTag", resourceCulture);
            }
        }
        
        public static string EnterProject {
            get {
                return ResourceManager.GetString("EnterProject", resourceCulture);
            }
        }
        
        public static string PasswordResetExplanation {
            get {
                return ResourceManager.GetString("PasswordResetExplanation", resourceCulture);
            }
        }
        
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        public static string PasswordResetEmailDoesNotExistError {
            get {
                return ResourceManager.GetString("PasswordResetEmailDoesNotExistError", resourceCulture);
            }
        }
        
        public static string PasswordResetGeneralError {
            get {
                return ResourceManager.GetString("PasswordResetGeneralError", resourceCulture);
            }
        }
        
        public static string PasswordResetOfflineError {
            get {
                return ResourceManager.GetString("PasswordResetOfflineError", resourceCulture);
            }
        }
        
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        public static string GoogleLogin {
            get {
                return ResourceManager.GetString("GoogleLogin", resourceCulture);
            }
        }
        
        public static string GoogleSignUp {
            get {
                return ResourceManager.GetString("GoogleSignUp", resourceCulture);
            }
        }
        
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        public static string LastWeek {
            get {
                return ResourceManager.GetString("LastWeek", resourceCulture);
            }
        }
        
        public static string ThisMonth {
            get {
                return ResourceManager.GetString("ThisMonth", resourceCulture);
            }
        }
        
        public static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        public static string ThisYear {
            get {
                return ResourceManager.GetString("ThisYear", resourceCulture);
            }
        }
        
        public static string WorkingOnThis {
            get {
                return ResourceManager.GetString("WorkingOnThis", resourceCulture);
            }
        }
        
        public static string WorkingOnThese {
            get {
                return ResourceManager.GetString("WorkingOnThese", resourceCulture);
            }
        }
        
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        public static string NoTagsInfoMessage {
            get {
                return ResourceManager.GetString("NoTagsInfoMessage", resourceCulture);
            }
        }
        
        public static string NoProjectsInfoMessage {
            get {
                return ResourceManager.GetString("NoProjectsInfoMessage", resourceCulture);
            }
        }
        
        public static string MondayInitial {
            get {
                return ResourceManager.GetString("MondayInitial", resourceCulture);
            }
        }
        
        public static string TuesdayInitial {
            get {
                return ResourceManager.GetString("TuesdayInitial", resourceCulture);
            }
        }
        
        public static string WednesdayInitial {
            get {
                return ResourceManager.GetString("WednesdayInitial", resourceCulture);
            }
        }
        
        public static string ThursdayInitial {
            get {
                return ResourceManager.GetString("ThursdayInitial", resourceCulture);
            }
        }
        
        public static string FridayInitial {
            get {
                return ResourceManager.GetString("FridayInitial", resourceCulture);
            }
        }
        
        public static string SaturdayInitial {
            get {
                return ResourceManager.GetString("SaturdayInitial", resourceCulture);
            }
        }
        
        public static string SundayInitial {
            get {
                return ResourceManager.GetString("SundayInitial", resourceCulture);
            }
        }
        
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        public static string WorkspaceChangedAlertTitle {
            get {
                return ResourceManager.GetString("WorkspaceChangedAlertTitle", resourceCulture);
            }
        }
        
        public static string WorkspaceChangedAlertMessage {
            get {
                return ResourceManager.GetString("WorkspaceChangedAlertMessage", resourceCulture);
            }
        }
        
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        public static string StartTimeEntry {
            get {
                return ResourceManager.GetString("StartTimeEntry", resourceCulture);
            }
        }
        
        public static string MostRecentEntry {
            get {
                return ResourceManager.GetString("MostRecentEntry", resourceCulture);
            }
        }
        
        public static string NoEmailErrorTitle {
            get {
                return ResourceManager.GetString("NoEmailErrorTitle", resourceCulture);
            }
        }
        
        public static string NoEmailErrorMessage {
            get {
                return ResourceManager.GetString("NoEmailErrorMessage", resourceCulture);
            }
        }
        
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string DeleteThisTimeEntry {
            get {
                return ResourceManager.GetString("DeleteThisTimeEntry", resourceCulture);
            }
        }
        
        public static string DiscardThisTimeEntry {
            get {
                return ResourceManager.GetString("DiscardThisTimeEntry", resourceCulture);
            }
        }
        
        public static string DiscardEditingChanges {
            get {
                return ResourceManager.GetString("DiscardEditingChanges", resourceCulture);
            }
        }
        
        public static string DurationFormatClassic {
            get {
                return ResourceManager.GetString("DurationFormatClassic", resourceCulture);
            }
        }
        
        public static string DurationFormatImproved {
            get {
                return ResourceManager.GetString("DurationFormatImproved", resourceCulture);
            }
        }
        
        public static string DurationFormatDecimal {
            get {
                return ResourceManager.GetString("DurationFormatDecimal", resourceCulture);
            }
        }
        
        public static string ContinueLastEntry {
            get {
                return ResourceManager.GetString("ContinueLastEntry", resourceCulture);
            }
        }
        
        public static string TapToRetry {
            get {
                return ResourceManager.GetString("TapToRetry", resourceCulture);
            }
        }
        
        public static string TimeEntrySuggestion {
            get {
                return ResourceManager.GetString("TimeEntrySuggestion", resourceCulture);
            }
        }
        
        public static string EmailIsAlreadyUsedError {
            get {
                return ResourceManager.GetString("EmailIsAlreadyUsedError", resourceCulture);
            }
        }
        
        public static string TryLoggingInInstead {
            get {
                return ResourceManager.GetString("TryLoggingInInstead", resourceCulture);
            }
        }
        
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        public static string SignUpCountryRequired {
            get {
                return ResourceManager.GetString("SignUpCountryRequired", resourceCulture);
            }
        }
    }
}
