//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toggl.Foundation {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Toggl.Foundation.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string OnboardingTrackPageCopy {
            get {
                return ResourceManager.GetString("OnboardingTrackPageCopy", resourceCulture);
            }
        }
        
        public static string OnboardingLogPageCopy {
            get {
                return ResourceManager.GetString("OnboardingLogPageCopy", resourceCulture);
            }
        }
        
        public static string OnboardingSummaryPageCopy {
            get {
                return ResourceManager.GetString("OnboardingSummaryPageCopy", resourceCulture);
            }
        }
        
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        public static string LoginSignUpEmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpEmailPlaceholder", resourceCulture);
            }
        }
        
        public static string LoginSignUpPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpPasswordPlaceholder", resourceCulture);
            }
        }
        
        public static string LoginNextButton {
            get {
                return ResourceManager.GetString("LoginNextButton", resourceCulture);
            }
        }
        
        public static string LoginBackButton {
            get {
                return ResourceManager.GetString("LoginBackButton", resourceCulture);
            }
        }
        
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        public static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        public static string TimeEntriesLogEmptyStateTitle {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateTitle", resourceCulture);
            }
        }
        
        public static string TimeEntriesLogEmptyStateText {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateText", resourceCulture);
            }
        }
        
        public static string TimeEntriesLogEmptyStateButton {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateButton", resourceCulture);
            }
        }
        
        public static string TimeEntriesLogEmptyStateWelcomeTitle {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateWelcomeTitle", resourceCulture);
            }
        }
        
        public static string TimeEntriesLogEmptyStateWelcomeText {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateWelcomeText", resourceCulture);
            }
        }
        
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        public static string GenericLoginError {
            get {
                return ResourceManager.GetString("GenericLoginError", resourceCulture);
            }
        }
        
        public static string StartTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("StartTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        public static string SettingsSyncInProgressTitle {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressTitle", resourceCulture);
            }
        }
        
        public static string SettingsSyncInProgressMessage {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressMessage", resourceCulture);
            }
        }
        
        public static string SettingsSyncInProgressButtonSignOutAnyway {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressButtonSignOutAnyway", resourceCulture);
            }
        }
        
        public static string UnitMin {
            get {
                return ResourceManager.GetString("UnitMin", resourceCulture);
            }
        }
        
        public static string UnitSecond {
            get {
                return ResourceManager.GetString("UnitSecond", resourceCulture);
            }
        }
        
        public static string SuggestionsHeader {
            get {
                return ResourceManager.GetString("SuggestionsHeader", resourceCulture);
            }
        }
        
        public static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        public static string NoProject {
            get {
                return ResourceManager.GetString("NoProject", resourceCulture);
            }
        }
        
        public static string SyncCompleted {
            get {
                return ResourceManager.GetString("SyncCompleted", resourceCulture);
            }
        }
        
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        public static string PullDownToRefresh {
            get {
                return ResourceManager.GetString("PullDownToRefresh", resourceCulture);
            }
        }
        
        public static string ReleaseToRefresh {
            get {
                return ResourceManager.GetString("ReleaseToRefresh", resourceCulture);
            }
        }
        
        public static string SuggestionsEmptyStateTitle {
            get {
                return ResourceManager.GetString("SuggestionsEmptyStateTitle", resourceCulture);
            }
        }
        
        public static string SuggestionsEmptyStateText {
            get {
                return ResourceManager.GetString("SuggestionsEmptyStateText", resourceCulture);
            }
        }
        
        public static string DifferentWorkspaceAlertTitle {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertTitle", resourceCulture);
            }
        }
        
        public static string DifferentWorkspaceAlertMessage {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertMessage", resourceCulture);
            }
        }
        
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
    }
}
