//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toggl.Foundation {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toggl.Foundation.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add client.
        /// </summary>
        public static string AddClient {
            get {
                return ResourceManager.GetString("AddClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add description.
        /// </summary>
        public static string AddDescription {
            get {
                return ResourceManager.GetString("AddDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/filter project.
        /// </summary>
        public static string AddFilterProjects {
            get {
                return ResourceManager.GetString("AddFilterProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/filter tags.
        /// </summary>
        public static string AddFilterTags {
            get {
                return ResourceManager.GetString("AddFilterTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a project.
        /// </summary>
        public static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a tag.
        /// </summary>
        public static string AddTags {
            get {
                return ResourceManager.GetString("AddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tag.
        /// </summary>
        public static string CreateTag {
            get {
                return ResourceManager.GetString("CreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change workspace?.
        /// </summary>
        public static string DifferentWorkspaceAlertMessage {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected a project from another workspace..
        /// </summary>
        public static string DifferentWorkspaceAlertTitle {
            get {
                return ResourceManager.GetString("DifferentWorkspaceAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we’re having trouble logging you in.
        ///Please try again..
        /// </summary>
        public static string GenericLoginError {
            get {
                return ResourceManager.GetString("GenericLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we’re having trouble signing you up. Please try again.
        /// </summary>
        public static string GenericSignUpError {
            get {
                return ResourceManager.GetString("GenericSignUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect email/password. Please, try again..
        /// </summary>
        public static string IncorrectEmailOrPassword {
            get {
                return ResourceManager.GetString("IncorrectEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect password. Please, try again.
        /// </summary>
        public static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string LoginBackButton {
            get {
                return ResourceManager.GetString("LoginBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string LoginForgotPassword {
            get {
                return ResourceManager.GetString("LoginForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string LoginNextButton {
            get {
                return ResourceManager.GetString("LoginNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string LoginSignUpEmailPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpEmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginSignUpPasswordPlaceholder {
            get {
                return ResourceManager.GetString("LoginSignUpPasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No client.
        /// </summary>
        public static string NoClient {
            get {
                return ResourceManager.GetString("NoClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Project.
        /// </summary>
        public static string NoProject {
            get {
                return ResourceManager.GetString("NoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your most used 
        ///time entries first.
        /// </summary>
        public static string OnboardingLogPageCopy {
            get {
                return ResourceManager.GetString("OnboardingLogPageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See a daily summary of
        ///your time usage.
        /// </summary>
        public static string OnboardingSummaryPageCopy {
            get {
                return ResourceManager.GetString("OnboardingSummaryPageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track your hours 
        ///with a single tap.
        /// </summary>
        public static string OnboardingTrackPageCopy {
            get {
                return ResourceManager.GetString("OnboardingTrackPageCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Unknown email. Please check that it&apos;s entered correctly..
        /// </summary>
        public static string PasswordResetEmailDoesNotExistError {
            get {
                return ResourceManager.GetString("PasswordResetEmailDoesNotExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email to reset your password..
        /// </summary>
        public static string PasswordResetExplanation {
            get {
                return ResourceManager.GetString("PasswordResetExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, we’re having trouble resetting your password. Please try again..
        /// </summary>
        public static string PasswordResetGeneralError {
            get {
                return ResourceManager.GetString("PasswordResetGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re offline. Please connect to the internet and try again..
        /// </summary>
        public static string PasswordResetOfflineError {
            get {
                return ResourceManager.GetString("PasswordResetOfflineError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We just sent you an email. Please follow the link in the email to reset your password..
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull down to refresh.
        /// </summary>
        public static string PullDownToRefresh {
            get {
                return ResourceManager.GetString("PullDownToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release to Refresh.
        /// </summary>
        public static string ReleaseToRefresh {
            get {
                return ResourceManager.GetString("ReleaseToRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default workspace.
        /// </summary>
        public static string SetDefaultWorkspace {
            get {
                return ResourceManager.GetString("SetDefaultWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SettingsDialogButtonSignOut {
            get {
                return ResourceManager.GetString("SettingsDialogButtonSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may lose your data when you sign out before the sync is complete..
        /// </summary>
        public static string SettingsSyncInProgressMessage {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re syncing your data.
        /// </summary>
        public static string SettingsSyncInProgressTitle {
            get {
                return ResourceManager.GetString("SettingsSyncInProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have some unsynced data. Any unsynced data will be lost..
        /// </summary>
        public static string SettingsUnsyncedMessage {
            get {
                return ResourceManager.GetString("SettingsUnsyncedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsynced data.
        /// </summary>
        public static string SettingsUnsyncedTitle {
            get {
                return ResourceManager.GetString("SettingsUnsyncedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be at least 6 characters..
        /// </summary>
        public static string SignUpPasswordRequirements {
            get {
                return ResourceManager.GetString("SignUpPasswordRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are you working on?.
        /// </summary>
        public static string StartTimeEntryPlaceholder {
            get {
                return ResourceManager.GetString("StartTimeEntryPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t tracked time for a while.
        ///Start the timer and your most used
        ///time entries will appear here..
        /// </summary>
        public static string SuggestionsEmptyStateText {
            get {
                return ResourceManager.GetString("SuggestionsEmptyStateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back!.
        /// </summary>
        public static string SuggestionsEmptyStateTitle {
            get {
                return ResourceManager.GetString("SuggestionsEmptyStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on these tasks?.
        /// </summary>
        public static string SuggestionsHeader {
            get {
                return ResourceManager.GetString("SuggestionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synced.
        /// </summary>
        public static string SyncCompleted {
            get {
                return ResourceManager.GetString("SyncCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing failed.
        /// </summary>
        public static string SyncFailed {
            get {
                return ResourceManager.GetString("SyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing....
        /// </summary>
        public static string Syncing {
            get {
                return ResourceManager.GetString("Syncing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service.
        /// </summary>
        public static string TermsOfService {
            get {
                return ResourceManager.GetString("TermsOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  See older entries .
        /// </summary>
        public static string TimeEntriesLogEmptyStateButton {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven’t tracked time for a while.
        ///Start the timer and your time entry log
        ///will appear here..
        /// </summary>
        public static string TimeEntriesLogEmptyStateText {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here....
        /// </summary>
        public static string TimeEntriesLogEmptyStateTitle {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the timer and your time entry log
        ///will appear here..
        /// </summary>
        public static string TimeEntriesLogEmptyStateWelcomeText {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing here yet.
        /// </summary>
        public static string TimeEntriesLogEmptyStateWelcomeTitle {
            get {
                return ResourceManager.GetString("TimeEntriesLogEmptyStateWelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        public static string UnitMin {
            get {
                return ResourceManager.GetString("UnitMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string UnitSecond {
            get {
                return ResourceManager.GetString("UnitSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspaces.
        /// </summary>
        public static string Workspaces {
            get {
                return ResourceManager.GetString("Workspaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
    }
}
